version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      - mvn package

artifacts:
  files:
    - target/springWebProj-0.0.1-SNAPSHOT
   
      
